### ISSUE TITLE
cIient is zoomed in

### ISSUE THREAD

**Issue by asatiki** [x00bence/Mecha#6] opened 2021-05-25 20:57 UTC
When i launch the hooked client, i cant see most of the client as it is liked zoomed in and doesnt fit to the window. I only see the parts as i captured in the screenshot.
![Screenshot_4](https://user-images.githubusercontent.com/84813632/119567406-f52c0d80-bdb4-11eb-9c4d-8df6321e82fd.png)

**Comment by x00bence** [comment] 2021-05-29 15:54
Hey,

[Duplicate issue (most likely)](https://github.com/x00bence/Mecha/issues/2)

I am currently aware of this. The problem is not with Mecha itself, but how the client works by default. This is due to the CEF build the League of Legends client uses, which has this issue.

I already have a (semi-)fix for this coming with the next update. 

I will leave this issue open until then.

**Comment by younamar** [comment] 2021-05-31 11:25
for the time being I solved the issue by switching to 100% in the scaling but the issue persists in the 125%

**Comment by XDivineGuardian** [comment] 2021-06-05 21:44
How can I set the scale to 100%? help pls

**Closed** 2022-03-14 03:37 UTC
Labels: bug
